# This action is to push the changes from this repo to mine's (alphaX86) such that the website is updated

name: Site Mirror

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: alphaX86/Indra_Site
        
    - name: Setup remote
      run: |
        git config user.name "Aadhitya A"
        git config user.email "aadhitya864@gmail.com"
        
    - name: Push and update changes
      run: |
        git checkout main
        git push -u origin main
        
    
      
